# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  # Base VM OS configuration.
  config.ssh.insert_key = false
  config.vm.synced_folder '.', '/vagrant', disabled: true
  # General VirtualBox VM configuration.
  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.cpus = 1
    v.linked_clone = true
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end
  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 1
    libvirt.memory = 1024
  end
  # ubuntu.
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "peru/ubuntu-20.04-desktop-amd64"
#    config.vm.box_version = "20210601.01"
    ubuntu.vm.hostname = "ubuntu.vm"
    ubuntu.vm.network :private_network, ip: "192.168.2.3"
    #ubuntu.vm.provision "shell",
    #  inline: "sudo yum update -y"
    ubuntu.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--cpus", 1]
      v.customize ["modifyvm", :id, "--vram", 128]
      v.customize ["modifyvm", :id, "--accelerate3d", "on"]
    end
  end
end
