# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  # Base VM OS configuration.
  config.ssh.insert_key = false
  config.vm.synced_folder '.', '/vagrant', disabled: true
  # General VirtualBox VM configuration.
  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.cpus = 1
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end
  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 1
    libvirt.memory = 1024
  end
  # target1.
  config.vm.define "target1" do |target1|
    target1.vm.box = "codeup/Ubuntu-20.04-GUI"
    target1.vm.hostname = "target1.ubuntu.vm"
    target1.vm.network :private_network, ip: "192.168.2.3"
    #target1.vm.provision "shell",
    #  inline: "sudo yum update -y"
    target1.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--cpus", 1]
      v.customize ["modifyvm", :id, "--vram", 128]
      v.customize ["modifyvm", :id, "--accelerate3d", "on"]
    end
    target1.vm.provider :libvirt do |libvirt|
      libvirt.memory = 1024
      libvirt.cpus = 1
      libvirt.video_vram = 128
    end
  end
  # Server2.
  config.vm.define "target2" do |target2|
    target2.vm.box = "centos/8"
    target2.vm.hostname = "target2.centos.vm"
    target2.vm.network :private_network, ip: "192.168.2.4"
    #target2.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: ".git/"
    #target2.vm.provision "shell",
    #  inline: "sudo yum update -y"
    target2.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--cpus", 2]
      v.customize ["modifyvm", :id, "--vram", 128]
      v.customize ["modifyvm", :id, "--accelerate3d", "on"]
    end
    target2.vm.provider :libvirt do |libvirt|
      libvirt.memory = 1024
      libvirt.cpus = 1
      libvirt.video_vram = 128
    end
  end

# Kali box.
  # Kali Linux Hacker Box.
  config.vm.define "hackerbox" do |hackerbox|
    hackerbox.vm.hostname = "HackerBox.vm"
    hackerbox.vm.network :private_network, ip: "192.168.2.42"
    config.vm.box = "kalilinux/rolling"
    config.ssh.insert_key = false
    hackerbox.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 4096]
      v.customize ["modifyvm", :id, "--cpus", 2]
      v.customize ["modifyvm", :id, "--vram", 128]
      v.customize ["modifyvm", :id, "--accelerate3d", "on"]
    end
    hackerbox.vm.provider :libvirt do |libvirt|
      libvirt.memory = 4096
      libvirt.cpus = 2
      libvirt.video_vram = 128
    end
  end
end
